name = "french-learning-app"
main = "index.py"
compatibility_date = "2024-05-15"
compatibility_flags = ["python_workers"]
workers_dev = true

[build]
command = ""

[[build.upload]]
format = "python"
dir = "./"
